function createMatclustFile(OutputPath)
%createMatclustFile(fileName,destFolder)
%saves the spike data in one nTrodes's extracted file for spikes as a file that matclust can open
%filename -- the name to give the files (i.e, 'tetrode1')
%destFolder -- the path to where the new file will be saved

if nargin<1
    error('please provide the path to the files containing\nthe snippets and spike arrival time generated by extract_logger_data\n');
end


Snippets_file = dir(fullfile(OutputPath, '*Tetrode_spikes_snippets*'));
SpikeTimes_file = dir(fullfile(OutputPath, '*Tetrode_spikes_time*'));


Num_tetrodes = length(Snippets_file);
for Tetrode_i=1:Num_tetrodes % for each of the electrode bundles, eg. tetrodes
    load(fullfile(SpikeTimes_file(Tetrode_i).folder, SpikeTimes_file(Tetrode_i).name), 'Spike_arrival_times', 'BatID', 'Date');
    load(fullfile(Snippets_file(Tetrode_i).folder, Snippets_file(Tetrode_i).name), 'Snippets');
    TetrodeID = SpikeTimes_file(Tetrode_i).name(end-4);
    if ~isempty(Spike_arrival_times) % check if the electrode bundle has no spikes (eg. if all its channels are inactive)
        % Saving waveforms features of spikes in matclust format
        disp(['Saving spikes from tetrode '  TetrodeID '...'])
        MatClust_Filename=fullfile(OutputPath,sprintf('%s_%s_MatClust%s.mat', BatID, Date,TetrodeID));
        Snippets_dim = size(Snippets); % 1st dim = length one snippet, 2nd dim = # channels, 3rd dim = #spikes
        filedata.paramnames = cell(Snippets_dim(2)*6+1);
        filedata.params = nan(Snippets_dim(3), Snippets_dim(2)*6+1);
        
        % save spike time
        fprintf(1,'Saving spike times\n')
        pp=1;
        filedata.paramnames{pp} = 'Time';
        filedata.params(:,pp) = Spike_arrival_times;
        
        % save spike peaks
        fprintf(1,'Saving spike peaks\n')
        for ch = 1:Snippets_dim(2)
            pp=pp+1;
            filedata.paramnames{pp} = ['Peak_',num2str(ch),' (uV)'];
            filedata.params(:,pp) = max(Snippets(:,ch,:),[],1);
        end
        
        % save valley
        fprintf(1,'Saving spike valleys\n')
        for ch = 1:Snippets_dim(2)
            pp=pp+1;
            filedata.paramnames{pp} = ['Valley_',num2str(ch),' (uV)'];
            filedata.params(:,pp) = min(Snippets(:,ch,:),[],1);
        end
        
        % save amplitude
        fprintf(1,'Saving spike amplitude\n')
        for ch = 1:Snippets_dim(2)
            pp=pp+1;
            filedata.paramnames{pp} = ['Amp_',num2str(ch),' (uV)'];
            filedata.params(:,pp) = max(Snippets(:,ch,:),[],1) - min(Snippets(:,ch,:),[],1);
        end
        
        
        % Reorganize the spike data to perform a PCA accross channels
        fprintf(1,'Running PCA on snippets.... ')
        Spike_Allsnippets = nan(Snippets_dim(3),Snippets_dim(1)*Snippets_dim(2));
        for ss=1:Snippets_dim(3)
            Spike_Allsnippets(ss,:) = reshape(Snippets(:,:,ss),1, Snippets_dim(1)*Snippets_dim(2));
        end
        % z-score the snippets per electrode
        for ee=1:Snippets_dim(2)
            local_data = reshape(Spike_Allsnippets(:,(1+(ee-1)*Snippets_dim(1)):ee*Snippets_dim(1)),1,Snippets_dim(1)*Snippets_dim(3));
            Spike_Allsnippets(:,(1+(ee-1)*Snippets_dim(1)):ee*Snippets_dim(1)) = (Spike_Allsnippets(:,(1+(ee-1)*Snippets_dim(1)):ee*Snippets_dim(1))-nanmean(local_data))/nanstd(local_data);
        end
        [PC, Projections] = pca(Spike_Allsnippets);
        
        % Plot the PCs
        figure();plot(PC(:,1),'k-','LineWidth',2)
        hold on;plot(PC(:,2),'r-','LineWidth',2)
        hold on;plot(PC(:,3),'b-','LineWidth',2)
        legend({'PC1' 'PC2' 'PC3'})
        
        % save PCA values
        fprintf(1,'Saving PCA values\n')
        for pc = 1:3
            pp=pp+1;
            filedata.paramnames{pp} = ['PC' num2str(pc)];
            filedata.params(:,pp) = Projections(:,pc);
        end
    else
        disp('No data for this file');
        filedata = [];
    end
    
    
    %-----------------------------------
    if (~isempty(filedata))
        filedata.filename = MatClust_Filename;
        save(MatClust_Filename, '-v7.3', 'filedata');
    end
    fprintf(1,'ALL DONE\n')
end